"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = """$directory$line_break$character"""
right_format = """$all"""

[package]
disabled = true

[character]
error_symbol = "[!](bold red)"

[directory]
truncation_length = 5

[golang]
symbol = " "
format = "[$symbol($version)](bold cyan)"

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = ' '

[nodejs]
format = "[$symbol$version]($style)"
detect_files = ["package.json"]
