[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

# Hyprland
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen/matugen-hyprland.conf'
post_hook = 'hyprctl reload'

# Waybar
[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/matugen-colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Kitty
[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/matugen-kitty.conf'
post_hook = "kitty @ set-colors -a -c ~/.config/kitty/matugen-kitty.conf"

# GTK
[templates.gtk3]
input_path = './templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = './templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync//matugen-swaync.css'
post_hook = 'swaync-client -rs'


# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

# Pywalfox
[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

# Zathura
[templates.zathura]
input_path = '~/.config/matugen/templates/matugen-zathurarc'
output_path = '~/.config/zathura/matugen-zathurarc'

# Wlogout
[templates.Wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/matugen/matugen-wlogout.css'
